# Default to H2 unless a specific profile is provided
spring.profiles.active=h2
server.forward-headers-strategy=native
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto
# Ensure Tomcat handles forwarded headers
server.tomcat.forward-headers-strategy=native
