server.forward-headers-strategy=framework

server.privateKey=${SERVER_PRIVATE_KEY_JSON}
# Server public key in JWK format
server.publicKey=${SERVER_PUBLIC_KEY_JSON}

server.port=8081


spring.jackson.serialization.write-dates-as-timestamps=false
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.endpoints.web.base-path=/api/actuator

# Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.balanceService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.balanceService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.balanceService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.balanceService.waitDurationInOpenState=60s
resilience4j.circuitbreaker.instances.balanceService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.balanceService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.balanceService.recordExceptions=java.lang.Exception
resilience4j.circuitbreaker.instances.balanceService.ignoreExceptions=java.lang.IllegalArgumentException

# Time Limiter Configuration
resilience4j.timelimiter.instances.balanceService.timeoutDuration=5s

# Logging configuration for circuit breaker events
logging.level.io.github.resilience4j.circuitbreaker=DEBUG
logging.level.com.adorsys.webank.obs.serviceimpl.BalanceServiceImpl=DEBUG
