name: Build and Push Docker Image (Testing)
on:
  push:
    branches: ['test-worflow-for-image']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn -f online-banking-app/pom.xml clean package -DskipTests

      - name: Verify JAR File Exists
        run: ls -l ./online-banking-app/target/online-banking-app-0.1-SNAPSHOT.jar

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/adorsys-gis/webank-online-banking:latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/adorsys-gis/webank-online-banking:latest