name: Build and Push Docker Image (Testing)
on:
  push:
    branches:
      - test-workflow-for-image
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/adorsys-gis/webank-online-banking:latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/adorsys-gis/webank-online-banking:latest