name: Build and Push Native Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GraalVM 22 with Native Image
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set up Maven settings.xml
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github-webank</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.WEBANK_ACCESS_TOKEN }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      - name: Build Native Executable
        run: mvn -Pnative native:compile -DskipTests

      - name: Verify Native Binary Exists
        run: |
          if [ ! -f ./online-banking-app/target/online-banking-app ]; then
            echo "Native binary not found!" && exit 1
          fi

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker Image with Native Binary
        run: |
          docker build \
            --build-arg BUILD_TYPE=native \
            -t ghcr.io/adorsys-gis/webank-online-banking:${{ github.sha }} .

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/adorsys-gis/webank-online-banking:${{ github.sha }}