name: Run Load Test

on:
  workflow_dispatch:

jobs:
  load-test:
    runs-on: ubuntu-latest
    env:
      APP_URL: ${{ secrets.TARGET_URL }}
      SERVER_PRIVATE_KEY_JSON: ${{ secrets.SERVER_PRIVATE_KEY_JSON }}
      SERVER_PUBLIC_KEY_JSON: ${{ secrets.SERVER_PUBLIC_KEY_JSON }}

    defaults:
      run:
        working-directory: load-testing/artillery

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Update target to production
        run: |
          sed -i "s|http://localhost:8081|${TARGET_URL}|g" load_test.yml

      - name: Run Artillery Test
        run: npx artillery run load_test.yml -o load-test-report.json

      - name: Generate HTML Report
        run: npx artillery report load-test-report.json --output load-test-report.html

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: load-test-report
          path: load-testing/artillery/load-test-report.html
