  name: Run Load Test

  on:
    workflow_dispatch:
    push:
      branches:
        - feature/load-testing-webank-online-banking

  jobs:
    load-test:
      runs-on: ubuntu-latest
      env:
        APP_URL: ${{ secrets.TARGET_URL }}
        SERVER_PRIVATE_KEY_JSON: ${{ vars.SERVER_PRIVATE_KEY_JSON }}
        SERVER_PUBLIC_KEY_JSON: ${{ vars.SERVER_PUBLIC_KEY_JSON }}

      defaults:
        run:
          working-directory: load-testing/artillery

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'
            cache: 'npm'
            cache-dependency-path: load-testing/artillery/package-lock.json

        - name: Clear npm cache
          run: npm cache clean --force

        - name: Install Dependencies
          run: npm install

        - name: Verify Artillery Installation
          run: npx artillery --version

        - name: Verify Environment Variables
          run: |
            echo "APP_URL set: ${APP_URL:+set}"
            echo "SERVER_PRIVATE_KEY_JSON set: ${SERVER_PRIVATE_KEY_JSON:+set}"
            echo "SERVER_PUBLIC_KEY_JSON set: ${SERVER_PUBLIC_KEY_JSON:+set}"

        - name: Update target to production
          run: sed -i "s|http://localhost:8081|$APP_URL|g" load_test.yml

        - name: Run Artillery Test
          run: npx artillery run load_test.yml -o load-test-report.json
          env:
            SERVER_PRIVATE_KEY_JSON: ${{ secrets.SERVER_PRIVATE_KEY_JSON }}
            SERVER_PUBLIC_KEY_JSON: ${{ secrets.SERVER_PUBLIC_KEY_JSON }}

        - name: Generate HTML Report
          run: npx artillery report load-test-report.json --output load-test-report.html

        - name: Upload Report Artifact
          uses: actions/upload-artifact@v4
          with:
            name: load-test-reports
            path: |
              load-testing/artillery/load-test-report.json
              load-testing/artillery/load-test-report.html
          if: always()

        - name: Debug on Failure
          if: failure()
          run: |
            echo "Dumping package.json"
            cat package.json
            echo "Dumping load_test.yml"
            cat load_test.yml
            echo "Dumping helper.js"
            cat helper.js
            echo "Dumping npm logs"
            cat /home/runner/.npm/_logs/*.log || true
